// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'product_models.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Product _$ProductFromJson(Map<String, dynamic> json) => Product(
  id: json['id'] as String,
  name: json['name'] as String,
  code: json['code'] as String?,
  clientId: json['clientId'] as String,
  categoryId: json['categoryId'] as String,
  type: json['type'] as String,
  brand: json['brand'] as String?,
  sif: json['sif'] as String?,
  description: json['description'] as String?,
  showBrandOnLabel: json['showBrandOnLabel'] as bool?,
  showSifOnLabel: json['showSifOnLabel'] as bool?,
  showManufacturingBatchOnLabel: json['showManufacturingBatchOnLabel'] as bool?,
  showExpiryDateOnLabel: json['showExpiryDateOnLabel'] as bool?,
  weightUnit: json['weightUnit'] as String?,
  weight: json['weight'] as String?,
  quantity: json['quantity'] as String?,
  defaultStorageLocationId: json['defaultStorageLocationId'] as String?,
  customTemplateId: json['customTemplateId'] as String?,
  defaultPrinterId: json['defaultPrinterId'] as String?,
  shelfLifeAmbient: const SafeIntConverter().fromJson(json['shelfLifeAmbient']),
  shelfLifeRefrigerated: const SafeIntConverter().fromJson(
    json['shelfLifeRefrigerated'],
  ),
  shelfLifeFrozen: const SafeIntConverter().fromJson(json['shelfLifeFrozen']),
  barcode: json['barcode'] as String?,
  isActive: json['isActive'] as bool,
  isLabelOnly: json['isLabelOnly'] as bool?,
  showTimeOnLabel: json['showTimeOnLabel'] as bool?,
  createdAt: DateTime.parse(json['createdAt'] as String),
  updatedAt: DateTime.parse(json['updatedAt'] as String),
);

Map<String, dynamic> _$ProductToJson(Product instance) => <String, dynamic>{
  'id': instance.id,
  'name': instance.name,
  'code': instance.code,
  'clientId': instance.clientId,
  'categoryId': instance.categoryId,
  'type': instance.type,
  'brand': instance.brand,
  'sif': instance.sif,
  'description': instance.description,
  'showBrandOnLabel': instance.showBrandOnLabel,
  'showSifOnLabel': instance.showSifOnLabel,
  'showManufacturingBatchOnLabel': instance.showManufacturingBatchOnLabel,
  'showExpiryDateOnLabel': instance.showExpiryDateOnLabel,
  'weightUnit': instance.weightUnit,
  'weight': instance.weight,
  'quantity': instance.quantity,
  'defaultStorageLocationId': instance.defaultStorageLocationId,
  'customTemplateId': instance.customTemplateId,
  'defaultPrinterId': instance.defaultPrinterId,
  'shelfLifeAmbient': const SafeIntConverter().toJson(
    instance.shelfLifeAmbient,
  ),
  'shelfLifeRefrigerated': const SafeIntConverter().toJson(
    instance.shelfLifeRefrigerated,
  ),
  'shelfLifeFrozen': const SafeIntConverter().toJson(instance.shelfLifeFrozen),
  'barcode': instance.barcode,
  'isActive': instance.isActive,
  'isLabelOnly': instance.isLabelOnly,
  'showTimeOnLabel': instance.showTimeOnLabel,
  'createdAt': instance.createdAt.toIso8601String(),
  'updatedAt': instance.updatedAt.toIso8601String(),
};

CreateProductRequest _$CreateProductRequestFromJson(
  Map<String, dynamic> json,
) => CreateProductRequest(
  name: json['name'] as String,
  code: json['code'] as String?,
  clientId: json['clientId'] as String,
  categoryId: json['categoryId'] as String,
  type: json['type'] as String,
  brand: json['brand'] as String?,
  sif: json['sif'] as String?,
  showBrandOnLabel: json['showBrandOnLabel'] as bool?,
  showSifOnLabel: json['showSifOnLabel'] as bool?,
  showManufacturingBatchOnLabel: json['showManufacturingBatchOnLabel'] as bool?,
  showExpiryDateOnLabel: json['showExpiryDateOnLabel'] as bool?,
  weightUnit: json['weightUnit'] as String?,
  weight: json['weight'] as String?,
  quantity: json['quantity'] as String?,
  defaultStorageLocationId: json['defaultStorageLocationId'] as String?,
  customTemplateId: json['customTemplateId'] as String?,
  defaultPrinterId: json['defaultPrinterId'] as String?,
  currency: json['currency'] as String?,
  shelfLifeAmbient: const SafeIntConverter().fromJson(json['shelfLifeAmbient']),
  shelfLifeRefrigerated: const SafeIntConverter().fromJson(
    json['shelfLifeRefrigerated'],
  ),
  shelfLifeFrozen: const SafeIntConverter().fromJson(json['shelfLifeFrozen']),
  observations: json['observations'] as String?,
  barcode: json['barcode'] as String?,
  isActive: json['isActive'] as bool?,
  isLabelOnly: json['isLabelOnly'] as bool?,
  showTimeOnLabel: json['showTimeOnLabel'] as bool?,
);

Map<String, dynamic> _$CreateProductRequestToJson(
  CreateProductRequest instance,
) => <String, dynamic>{
  'name': instance.name,
  'code': instance.code,
  'clientId': instance.clientId,
  'categoryId': instance.categoryId,
  'type': instance.type,
  'brand': instance.brand,
  'sif': instance.sif,
  'showBrandOnLabel': instance.showBrandOnLabel,
  'showSifOnLabel': instance.showSifOnLabel,
  'showManufacturingBatchOnLabel': instance.showManufacturingBatchOnLabel,
  'showExpiryDateOnLabel': instance.showExpiryDateOnLabel,
  'weightUnit': instance.weightUnit,
  'weight': instance.weight,
  'quantity': instance.quantity,
  'defaultStorageLocationId': instance.defaultStorageLocationId,
  'customTemplateId': instance.customTemplateId,
  'defaultPrinterId': instance.defaultPrinterId,
  'currency': instance.currency,
  'shelfLifeAmbient': const SafeIntConverter().toJson(
    instance.shelfLifeAmbient,
  ),
  'shelfLifeRefrigerated': const SafeIntConverter().toJson(
    instance.shelfLifeRefrigerated,
  ),
  'shelfLifeFrozen': const SafeIntConverter().toJson(instance.shelfLifeFrozen),
  'observations': instance.observations,
  'barcode': instance.barcode,
  'isActive': instance.isActive,
  'isLabelOnly': instance.isLabelOnly,
  'showTimeOnLabel': instance.showTimeOnLabel,
};

UpdateProductRequest _$UpdateProductRequestFromJson(
  Map<String, dynamic> json,
) => UpdateProductRequest(
  name: json['name'] as String,
  code: json['code'] as String?,
  categoryId: json['categoryId'] as String,
  type: json['type'] as String,
  brand: json['brand'] as String?,
  sif: json['sif'] as String?,
  showBrandOnLabel: json['showBrandOnLabel'] as bool?,
  showSifOnLabel: json['showSifOnLabel'] as bool?,
  showManufacturingBatchOnLabel: json['showManufacturingBatchOnLabel'] as bool?,
  showExpiryDateOnLabel: json['showExpiryDateOnLabel'] as bool?,
  weightUnit: json['weightUnit'] as String?,
  weight: json['weight'] as String?,
  quantity: json['quantity'] as String?,
  defaultStorageLocationId: json['defaultStorageLocationId'] as String?,
  customTemplateId: json['customTemplateId'] as String?,
  defaultPrinterId: json['defaultPrinterId'] as String?,
  shelfLifeAmbient: const SafeIntConverter().fromJson(json['shelfLifeAmbient']),
  shelfLifeRefrigerated: const SafeIntConverter().fromJson(
    json['shelfLifeRefrigerated'],
  ),
  shelfLifeFrozen: const SafeIntConverter().fromJson(json['shelfLifeFrozen']),
  observations: json['observations'] as String?,
  barcode: json['barcode'] as String?,
  isActive: json['isActive'] as bool?,
  isLabelOnly: json['isLabelOnly'] as bool?,
  showTimeOnLabel: json['showTimeOnLabel'] as bool?,
);

Map<String, dynamic> _$UpdateProductRequestToJson(
  UpdateProductRequest instance,
) => <String, dynamic>{
  'name': instance.name,
  'code': instance.code,
  'categoryId': instance.categoryId,
  'type': instance.type,
  'brand': instance.brand,
  'sif': instance.sif,
  'showBrandOnLabel': instance.showBrandOnLabel,
  'showSifOnLabel': instance.showSifOnLabel,
  'showManufacturingBatchOnLabel': instance.showManufacturingBatchOnLabel,
  'showExpiryDateOnLabel': instance.showExpiryDateOnLabel,
  'weightUnit': instance.weightUnit,
  'weight': instance.weight,
  'quantity': instance.quantity,
  'defaultStorageLocationId': instance.defaultStorageLocationId,
  'customTemplateId': instance.customTemplateId,
  'defaultPrinterId': instance.defaultPrinterId,
  'shelfLifeAmbient': const SafeIntConverter().toJson(
    instance.shelfLifeAmbient,
  ),
  'shelfLifeRefrigerated': const SafeIntConverter().toJson(
    instance.shelfLifeRefrigerated,
  ),
  'shelfLifeFrozen': const SafeIntConverter().toJson(instance.shelfLifeFrozen),
  'observations': instance.observations,
  'barcode': instance.barcode,
  'isActive': instance.isActive,
  'isLabelOnly': instance.isLabelOnly,
  'showTimeOnLabel': instance.showTimeOnLabel,
};
